server:
  port: 8000
spring:
  redis:
    database: 5
    host: 114.55.34.44
    password: root
    port: 6379
    timeout: 3000ms
    jedis:
      pool:
        max-active: 2000
        max-idle: 500
        max-wait: 1000ms
        min-idle: 50

